'''
Created by Conrad Bucholtz, 9/21/2018

Problem 2:

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.



-----MY SOLUTION-----

This program needs just one function
'''

def fibonacciSum(a, b, stop): #takes first two numbers, and stopping point
    x = 0 #x is the sum
    #the loop will iterate with pairs of fibonacci numbers
    #a will always be the smaller number
    while (a<stop): #iterate until a < stopping point
        if (a%2 == 0):
            x += a #add a if even
        if (b<stop and b%2 == 0): #recheck that b isn't too large
            x += b #add b if even
        #get the next two fibonacci numbers
        a += b
        b += a
    return x

'''
Print the solution with given conditions
'''
print(fibonacciSum(1,2,4000000))